main:
    n_components: 2
    n_neighbours: 30
    min_distance: 0.0
    min_samples: 10
<<<<<<< HEAD
<<<<<<< HEAD
    min_cluster_size: 10
    max_cluster_size: 50
=======
    min_cluster_size: 20
    max_cluster_size: 200
>>>>>>> dbc44a0d0a8131a53fdd1d62f5479129ba19081f
=======
    min_cluster_size: 20
    max_cluster_size: 200
>>>>>>> dbc44a0d0a8131a53fdd1d62f5479129ba19081f
    cluster_selection_epsilon: 0.0
    metric: euclidean
    alpha: 1.0
    p: 2
    cluster_selection_method: eom
    allow_single_cluster: False
    gen_min_span_tree: False
    handle: None
    connectivity: knn
    output_type: None
    entity_embedding_path: s3://experiment-logging/storage/gdelt-embeddings/openke-graph-training.3ed8b6262cd34d52b092039d0ee1d374/artifacts/transe.ckpt/transe.ckpt
    #doc_emb_path: s3://experiment-logging/storage/gdelt-embeddings/combine-graph-document-embeddings.ed6a3f66d3f14499916b568e7aadf974/artifacts/document-embeddings-2021/total_document_embeds.pt
    doc_emb_path: s3://experiment-logging/storage/gdelt-embeddings/graph-clustering-2020.f20767d119f44dc69868df857f449cee/artifacts/temporal_list_by_idx/temporal_list_by_idx.pkl